services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - valkey-net

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - valkey
    networks:
      - valkey-net
  
  mysql:
    image: mariadb:10.6
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: valkey_for_laravel_secret
    volumes:
      - ./mysql:/var/lib/mysql
      - ./databases-backup.sql:/docker-entrypoint-initdb.d/databases-backup.sql
    networks:
      - valkey-net

  valkey:
    build:
      context: .
      dockerfile: valkey.dockerfile
    ports:
      - 6379:6379
    networks:
      - valkey-net

networks:
  valkey-net:
    driver: bridge
